apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pipeline-end-end-test
  description: Backstage don't creating inactive services
spec:
  type: service
  lifecycle: experimental
  owner: group:default/developer-experience
